import { ElementNode, ElementType, SidebarCategory } from "@/types";

// Plain JSON templates — fully serializable
// x, y are set to 0 here; the store assigns real position on addElement
export const templates: Record<ElementType, Omit<ElementNode, "id">> = {
    section: {
        type: "section",
        label: "Section",
        props: {},
        styles: {
            padding: "40px 20px",
            minHeight: "120px",
            backgroundColor: "#ffffff",
        },
        x: 0, y: 0, w: 800, h: 200,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    container: {
        type: "container",
        label: "Container",
        props: {},
        styles: {
            padding: "20px",
            minHeight: "80px",
            backgroundColor: "transparent",
            border: "1px dashed #d1d5db",
            borderRadius: "8px",
        },
        x: 0, y: 0, w: 400, h: 200,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    columns: {
        type: "columns",
        label: "Columns",
        props: { columnCount: 2 },
        styles: {
            display: "flex",
            gap: "16px",
            padding: "20px",
            minHeight: "80px",
        },
        x: 0, y: 0, w: 600, h: 200,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    stack: {
        type: "stack",
        label: "Stack",
        props: { direction: "vertical" },
        styles: {
            display: "flex",
            flexDirection: "column",
            gap: "12px",
            padding: "16px",
            minHeight: "60px",
        },
        x: 0, y: 0, w: 400, h: 200,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    title: {
        type: "title",
        label: "Title",
        props: { content: "Add a Title", level: 2 },
        styles: {
            fontSize: "32px",
            fontWeight: "700",
            color: "#1a1a2e",
            margin: "0",
            lineHeight: "1.2",
            textAlign: "left",
            fontFamily: "Inter",
        },
        x: 0, y: 0, w: 400, h: 50,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    text: {
        type: "text",
        label: "Text",
        props: { content: "Edit this text" },
        styles: {
            fontSize: "16px",
            color: "#374151",
            lineHeight: "1.6",
            textAlign: "left",
            fontFamily: "Inter",
        },
        x: 0, y: 0, w: 300, h: 30,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    paragraph: {
        type: "paragraph",
        label: "Paragraph",
        props: {
            content:
                "This is a paragraph. Click to edit and add your own text. Customize the font, size, and color in the properties panel.",
        },
        styles: {
            fontSize: "15px",
            color: "#4b5563",
            lineHeight: "1.7",
            maxWidth: "680px",
            textAlign: "left",
            fontFamily: "Inter",
        },
        x: 0, y: 0, w: 500, h: 80,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    button: {
        type: "button",
        label: "Button",
        props: { label: "Click me" },
        styles: {
            backgroundColor: "#3b82f6",
            color: "#ffffff",
            padding: "12px 28px",
            borderRadius: "6px",
            fontSize: "15px",
            fontWeight: "600",
            cursor: "pointer",
            border: "none",
            display: "inline-block",
            textAlign: "center",
            fontFamily: "Inter",
        },
        animation: { type: "none", duration: 0.3 },
        actions: { type: "none" },
        x: 0, y: 0, w: 160, h: 44,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    image: {
        type: "image",
        label: "Image",
        props: {
            src: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop",
            alt: "Placeholder image",
            objectFit: "cover",
        },
        styles: {
            maxWidth: "100%",
            borderRadius: "8px",
            display: "block",
        },
        x: 0, y: 0, w: 400, h: 280,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    video: {
        type: "video",
        label: "Video",
        props: {
            src: "https://www.w3schools.com/html/mov_bbb.mp4",
            autoplay: false,
            controls: true,
            loop: false,
            muted: false,
        },
        styles: {
            width: "100%",
            maxWidth: "640px",
            borderRadius: "8px",
        },
        x: 0, y: 0, w: 480, h: 300,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    gallery: {
        type: "gallery",
        label: "Gallery",
        props: { columns: 3, gap: 8 },
        styles: {
            display: "grid",
            gridTemplateColumns: "repeat(3, 1fr)",
            gap: "8px",
            padding: "8px",
        },
        x: 0, y: 0, w: 500, h: 250,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    form: {
        type: "form",
        label: "Form",
        props: {
            requestMethod: "POST",
            requestUrl: "/api/contact",
        },
        styles: {
            padding: "24px",
            backgroundColor: "#ffffff",
            borderRadius: "12px",
            border: "1px solid #e5e7eb",
        },
        actions: { type: "submit" },
        x: 0, y: 0, w: 400, h: 300,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [
            {
                id: "__form_label__",
                type: "text",
                label: "Form Label",
                props: { content: "Contact Us" },
                styles: { fontSize: "20px", fontWeight: "600", color: "#1a1a2e", marginBottom: "12px" },
                x: 0, y: 0, w: 360, h: 30,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
            {
                id: "__form_input_name__",
                type: "input",
                label: "Name Input",
                props: { name: "name", placeholder: "Your name", inputType: "text", required: true },
                styles: { padding: "10px 14px", border: "1px solid #d1d5db", borderRadius: "6px", fontSize: "14px", width: "100%", backgroundColor: "#fff", marginBottom: "10px" },
                x: 0, y: 0, w: 360, h: 40,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
            {
                id: "__form_input_email__",
                type: "input",
                label: "Email Input",
                props: { name: "email", placeholder: "Your email", inputType: "email", required: true },
                styles: { padding: "10px 14px", border: "1px solid #d1d5db", borderRadius: "6px", fontSize: "14px", width: "100%", backgroundColor: "#fff", marginBottom: "10px" },
                x: 0, y: 0, w: 360, h: 40,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
            {
                id: "__form_submit__",
                type: "button",
                label: "Submit",
                props: { label: "Submit" },
                styles: { backgroundColor: "#3b82f6", color: "#fff", padding: "10px 24px", borderRadius: "6px", fontSize: "14px", fontWeight: "600", border: "none", cursor: "pointer" },
                x: 0, y: 0, w: 120, h: 40,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
        ],
    },
    input: {
        type: "input",
        label: "Input",
        props: { placeholder: "Enter text...", inputType: "text", required: false },
        styles: {
            padding: "12px 16px",
            border: "1px solid #d1d5db",
            borderRadius: "8px",
            fontSize: "14px",
            width: "100%",
            backgroundColor: "#ffffff",
        },
        x: 0, y: 0, w: 300, h: 44,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    shape: {
        type: "shape",
        label: "Shape",
        props: { shapeType: "rectangle" },
        styles: {
            width: "120px",
            height: "120px",
            backgroundColor: "#6366f1",
            borderRadius: "12px",
        },
        x: 0, y: 0, w: 120, h: 120,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    divider: {
        type: "divider",
        label: "Divider",
        props: {},
        styles: {
            width: "100%",
            height: "1px",
            backgroundColor: "#e5e7eb",
            margin: "16px 0",
        },
        x: 0, y: 0, w: 500, h: 4,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    menu: {
        type: "menu",
        label: "Menu",
        props: {
            items: "Home,About,Services,Contact",
            menuStyle: "horizontal",
        },
        styles: {
            display: "flex",
            gap: "24px",
            padding: "12px 20px",
            backgroundColor: "#ffffff",
            borderRadius: "8px",
        },
        x: 0, y: 0, w: 500, h: 44,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    repeater: {
        type: "repeater",
        label: "Repeater",
        props: { repeatCount: 3, direction: "column" },
        styles: {
            display: "flex",
            flexDirection: "column",
            gap: "12px",
            padding: "16px",
            border: "1px dashed #a5b4fc",
            borderRadius: "8px",
        },
        x: 0, y: 0, w: 400, h: 200,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    frame: {
        type: "frame",
        label: "Frame",
        props: {
            src: "https://example.com",
        },
        styles: {
            width: "100%",
            height: "300px",
            border: "1px solid #d1d5db",
            borderRadius: "8px",
        },
        x: 0, y: 0, w: 500, h: 300,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    icon: {
        type: "icon",
        label: "Icon",
        props: { icon: "star", iconSize: 32, iconColor: "#374151" },
        styles: {},
        x: 0, y: 0, w: 48, h: 48,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    spacer: {
        type: "spacer",
        label: "Spacer",
        props: { spacerHeight: 40 },
        styles: {},
        x: 0, y: 0, w: 500, h: 40,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    socialbar: {
        type: "socialbar",
        label: "Social Bar",
        props: {
            facebook: true,
            twitter: true,
            instagram: true,
            linkedin: false,
            youtube: false,
            iconSize: 24,
            iconStyle: "filled",
        },
        styles: {
            display: "flex",
            gap: "12px",
            alignItems: "center",
        },
        x: 0, y: 0, w: 300, h: 48,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    accordion: {
        type: "accordion",
        label: "Accordion",
        props: { headerText: "Accordion Header", expanded: true },
        styles: {
            border: "1px solid #e5e7eb",
            borderRadius: "8px",
            overflow: "hidden",
        },
        x: 0, y: 0, w: 500, h: 200,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
    tabs: {
        type: "tabs",
        label: "Tabs",
        props: { tabTitles: "Tab 1,Tab 2,Tab 3", activeTab: 0 },
        styles: {
            border: "1px solid #e5e7eb",
            borderRadius: "8px",
            overflow: "hidden",
        },
        x: 0, y: 0, w: 600, h: 300,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [],
    },
};

// All sidebar element categories — Wix-style grouped by section
export const sidebarCategories: SidebarCategory[] = [
    {
        id: "sections",
        label: "Sections",
        icon: "section",
        items: [
            { type: "section", label: "Section", icon: "section" },
        ],
    },
    {
        id: "containers",
        label: "Containers",
        icon: "container",
        items: [
            { type: "container", label: "Container", icon: "container" },
            { type: "columns", label: "Columns", icon: "columns" },
            { type: "stack", label: "Stack", icon: "stack" },
        ],
    },
    {
        id: "layout",
        label: "Layout Tools",
        icon: "spacer",
        items: [
            { type: "spacer", label: "Spacer", icon: "spacer" },
            { type: "divider", label: "Divider", icon: "divider" },
        ],
    },
    {
        id: "text",
        label: "Text",
        icon: "title",
        items: [
            { type: "title", label: "Title", icon: "title" },
            { type: "text", label: "Text", icon: "text" },
            { type: "paragraph", label: "Paragraph", icon: "paragraph" },
        ],
    },
    {
        id: "buttons",
        label: "Buttons",
        icon: "button",
        items: [
            { type: "button", label: "Button", icon: "button" },
        ],
    },
    {
        id: "media",
        label: "Media",
        icon: "image",
        items: [
            { type: "image", label: "Image", icon: "image" },
            { type: "video", label: "Video", icon: "video" },
            { type: "gallery", label: "Gallery", icon: "gallery" },
        ],
    },
    {
        id: "menu",
        label: "Menu & Search",
        icon: "menu",
        items: [
            { type: "menu", label: "Menu", icon: "menu" },
        ],
    },
    {
        id: "decorative",
        label: "Decorative",
        icon: "shape",
        items: [
            { type: "shape", label: "Shape", icon: "shape" },
            { type: "icon", label: "Icon", icon: "icon" },
            { type: "divider", label: "Line", icon: "divider" },
        ],
    },
    {
        id: "forms",
        label: "Contact & Forms",
        icon: "form",
        items: [
            { type: "form", label: "Form", icon: "form" },
            { type: "input", label: "Input", icon: "input" },
        ],
    },
    {
        id: "embed",
        label: "Embed & Social",
        icon: "socialbar",
        items: [
            { type: "socialbar", label: "Social Bar", icon: "socialbar" },
            { type: "frame", label: "Embed Code", icon: "frame" },
        ],
    },
    {
        id: "advanced",
        label: "Advanced",
        icon: "repeater",
        items: [
            { type: "repeater", label: "Repeater", icon: "repeater" },
            { type: "accordion", label: "Accordion", icon: "accordion" },
            { type: "tabs", label: "Tabs", icon: "tabs" },
        ],
    },
];
