import { ElementNode } from "@/types";

export interface SiteTemplate {
    id: string;
    name: string;
    description: string;
    category: string;
    thumbnail: string;
    previewUrl: string;
    elements: any[];
}

// ═══════════════════════════════════════════════════════════
// Template 1 — Open: SaaS Landing Page
// ═══════════════════════════════════════════════════════════
const template1Elements: any[] = [
    // ─── Hero Section ───
    {
        type: "section",
        label: "Hero Section",
        props: {},
        styles: {
            padding: "0",
            minHeight: "600px",
            background: "linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%)",
            position: "relative",
            overflow: "hidden",
        },
        x: 0, y: 0, w: 1280, h: 600,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [
            {
                id: "__t1_nav__",
                type: "container",
                label: "Navigation Bar",
                props: {},
                styles: {
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    padding: "20px 60px",
                    backgroundColor: "transparent",
                },
                x: 0, y: 0, w: 1280, h: 70,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [
                    {
                        id: "__t1_logo__",
                        type: "title",
                        label: "Logo",
                        props: { content: "Open", level: 3 },
                        styles: { fontSize: "24px", fontWeight: "700", color: "#ffffff", fontFamily: "Inter" },
                        x: 0, y: 0, w: 100, h: 40,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                    {
                        id: "__t1_menu__",
                        type: "menu",
                        label: "Nav Menu",
                        props: { items: "Features,Pricing,Resources,Sign In", menuStyle: "horizontal" },
                        styles: { display: "flex", gap: "32px", padding: "0" },
                        x: 0, y: 0, w: 400, h: 40,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                ],
            },
            {
                id: "__t1_hero_content__",
                type: "container",
                label: "Hero Content",
                props: {},
                styles: {
                    padding: "80px 60px",
                    maxWidth: "700px",
                    backgroundColor: "transparent",
                    border: "none",
                },
                x: 0, y: 80, w: 700, h: 400,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [
                    {
                        id: "__t1_badge__",
                        type: "button",
                        label: "Badge",
                        props: { label: "✨ Open Pro — New release →" },
                        styles: {
                            backgroundColor: "rgba(99,102,241,0.2)",
                            color: "#a5b4fc",
                            padding: "6px 16px",
                            borderRadius: "999px",
                            fontSize: "13px",
                            fontWeight: "500",
                            border: "1px solid rgba(99,102,241,0.3)",
                            cursor: "pointer",
                            display: "inline-block",
                            textAlign: "center",
                        },
                        x: 0, y: 0, w: 220, h: 36,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                    {
                        id: "__t1_heading__",
                        type: "title",
                        label: "Hero Heading",
                        props: { content: "Create landing pages for your SaaS projects", level: 1 },
                        styles: {
                            fontSize: "52px",
                            fontWeight: "800",
                            color: "#ffffff",
                            lineHeight: "1.1",
                            fontFamily: "Inter",
                            letterSpacing: "-0.02em",
                        },
                        x: 0, y: 50, w: 640, h: 130,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                    {
                        id: "__t1_subtitle__",
                        type: "paragraph",
                        label: "Hero Subtitle",
                        props: { content: "Our landing page template works on all devices, so you only have to set it up once, and get beautiful results forever." },
                        styles: {
                            fontSize: "18px",
                            color: "#94a3b8",
                            lineHeight: "1.7",
                            fontFamily: "Inter",
                        },
                        x: 0, y: 200, w: 560, h: 60,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                    {
                        id: "__t1_cta__",
                        type: "button",
                        label: "CTA Button",
                        props: { label: "Start Free Trial →" },
                        styles: {
                            backgroundColor: "#6366f1",
                            color: "#ffffff",
                            padding: "14px 32px",
                            borderRadius: "8px",
                            fontSize: "16px",
                            fontWeight: "600",
                            border: "none",
                            cursor: "pointer",
                            display: "inline-block",
                            textAlign: "center",
                        },
                        x: 0, y: 290, w: 200, h: 50,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                ],
            },
        ],
    },
    // ─── Features Section ───
    {
        type: "section",
        label: "Features Section",
        props: {},
        styles: {
            padding: "80px 60px",
            minHeight: "400px",
            backgroundColor: "#0f172a",
        },
        x: 0, y: 600, w: 1280, h: 500,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [
            {
                id: "__t1_feat_heading__",
                type: "title",
                label: "Features Heading",
                props: { content: "Built for developers", level: 2 },
                styles: { fontSize: "36px", fontWeight: "700", color: "#ffffff", textAlign: "center", fontFamily: "Inter" },
                x: 0, y: 0, w: 1160, h: 50,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
            {
                id: "__t1_feat_sub__",
                type: "paragraph",
                label: "Features Subtitle",
                props: { content: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." },
                styles: { fontSize: "16px", color: "#94a3b8", textAlign: "center", lineHeight: "1.7", fontFamily: "Inter" },
                x: 0, y: 60, w: 1160, h: 50,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
            {
                id: "__t1_features_grid__",
                type: "columns",
                label: "Features Grid",
                props: { columnCount: 3 },
                styles: { display: "flex", gap: "24px", padding: "40px 0", minHeight: "250px" },
                x: 0, y: 130, w: 1160, h: 300,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [
                    {
                        id: "__t1_f1__",
                        type: "container",
                        label: "Feature 1",
                        props: {},
                        styles: { padding: "32px", backgroundColor: "#1e293b", borderRadius: "12px", border: "1px solid #334155", textAlign: "center" },
                        x: 0, y: 0, w: 360, h: 250,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [
                            {
                                id: "__t1_f1_icon__",
                                type: "icon",
                                label: "Feature Icon",
                                props: { icon: "star", iconSize: 32, iconColor: "#6366f1" },
                                styles: {},
                                x: 0, y: 0, w: 48, h: 48,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                            {
                                id: "__t1_f1_title__",
                                type: "title",
                                label: "Feature Title",
                                props: { content: "Instant Composing", level: 4 },
                                styles: { fontSize: "18px", fontWeight: "600", color: "#ffffff", fontFamily: "Inter" },
                                x: 0, y: 60, w: 296, h: 30,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                            {
                                id: "__t1_f1_desc__",
                                type: "text",
                                label: "Feature Description",
                                props: { content: "Build pixel-perfect landing pages quickly without writing a single line of code." },
                                styles: { fontSize: "14px", color: "#94a3b8", lineHeight: "1.6", fontFamily: "Inter" },
                                x: 0, y: 100, w: 296, h: 60,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                        ],
                    },
                    {
                        id: "__t1_f2__",
                        type: "container",
                        label: "Feature 2",
                        props: {},
                        styles: { padding: "32px", backgroundColor: "#1e293b", borderRadius: "12px", border: "1px solid #334155", textAlign: "center" },
                        x: 0, y: 0, w: 360, h: 250,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [
                            {
                                id: "__t1_f2_icon__",
                                type: "icon",
                                label: "Feature Icon",
                                props: { icon: "settings", iconSize: 32, iconColor: "#6366f1" },
                                styles: {},
                                x: 0, y: 0, w: 48, h: 48,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                            {
                                id: "__t1_f2_title__",
                                type: "title",
                                label: "Feature Title",
                                props: { content: "Powerful Settings", level: 4 },
                                styles: { fontSize: "18px", fontWeight: "600", color: "#ffffff", fontFamily: "Inter" },
                                x: 0, y: 60, w: 296, h: 30,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                            {
                                id: "__t1_f2_desc__",
                                type: "text",
                                label: "Feature Description",
                                props: { content: "Configure every aspect of your landing page with our intuitive settings panel." },
                                styles: { fontSize: "14px", color: "#94a3b8", lineHeight: "1.6", fontFamily: "Inter" },
                                x: 0, y: 100, w: 296, h: 60,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                        ],
                    },
                    {
                        id: "__t1_f3__",
                        type: "container",
                        label: "Feature 3",
                        props: {},
                        styles: { padding: "32px", backgroundColor: "#1e293b", borderRadius: "12px", border: "1px solid #334155", textAlign: "center" },
                        x: 0, y: 0, w: 360, h: 250,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [
                            {
                                id: "__t1_f3_icon__",
                                type: "icon",
                                label: "Feature Icon",
                                props: { icon: "check", iconSize: 32, iconColor: "#6366f1" },
                                styles: {},
                                x: 0, y: 0, w: 48, h: 48,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                            {
                                id: "__t1_f3_title__",
                                type: "title",
                                label: "Feature Title",
                                props: { content: "Production Ready", level: 4 },
                                styles: { fontSize: "18px", fontWeight: "600", color: "#ffffff", fontFamily: "Inter" },
                                x: 0, y: 60, w: 296, h: 30,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                            {
                                id: "__t1_f3_desc__",
                                type: "text",
                                label: "Feature Description",
                                props: { content: "Ship to production with confidence using our battle-tested components." },
                                styles: { fontSize: "14px", color: "#94a3b8", lineHeight: "1.6", fontFamily: "Inter" },
                                x: 0, y: 100, w: 296, h: 60,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                        ],
                    },
                ],
            },
        ],
    },
    // ─── CTA / Footer Section ───
    {
        type: "section",
        label: "CTA Section",
        props: {},
        styles: {
            padding: "80px 60px",
            minHeight: "300px",
            background: "linear-gradient(135deg, #1e293b 0%, #0f172a 100%)",
            textAlign: "center",
        },
        x: 0, y: 1100, w: 1280, h: 300,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [
            {
                id: "__t1_cta_heading__",
                type: "title",
                label: "CTA Heading",
                props: { content: "Get started today", level: 2 },
                styles: { fontSize: "36px", fontWeight: "700", color: "#ffffff", textAlign: "center", fontFamily: "Inter" },
                x: 0, y: 0, w: 1160, h: 50,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
            {
                id: "__t1_cta_sub__",
                type: "paragraph",
                label: "CTA Subtitle",
                props: { content: "Join thousands of developers who are already building with Open." },
                styles: { fontSize: "18px", color: "#94a3b8", textAlign: "center", fontFamily: "Inter" },
                x: 0, y: 60, w: 1160, h: 30,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
            {
                id: "__t1_cta_btn__",
                type: "button",
                label: "CTA Button",
                props: { label: "Start Building for Free →" },
                styles: {
                    backgroundColor: "#6366f1",
                    color: "#ffffff",
                    padding: "14px 32px",
                    borderRadius: "8px",
                    fontSize: "16px",
                    fontWeight: "600",
                    border: "none",
                    cursor: "pointer",
                    textAlign: "center",
                },
                x: 520, y: 120, w: 240, h: 50,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
        ],
    },
];

// ═══════════════════════════════════════════════════════════
// Template 2 — TailAdmin: Dashboard
// ═══════════════════════════════════════════════════════════
const template2Elements: any[] = [
    // ─── Top Header Bar ───
    {
        type: "section",
        label: "Dashboard Header",
        props: {},
        styles: {
            padding: "0",
            minHeight: "64px",
            backgroundColor: "#1c2434",
            display: "flex",
            alignItems: "center",
        },
        x: 0, y: 0, w: 1280, h: 64,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [
            {
                id: "__t2_header_container__",
                type: "container",
                label: "Header Content",
                props: {},
                styles: {
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    padding: "0 24px",
                    backgroundColor: "transparent",
                    border: "none",
                    width: "100%",
                },
                x: 0, y: 0, w: 1280, h: 64,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [
                    {
                        id: "__t2_logo__",
                        type: "title",
                        label: "Dashboard Logo",
                        props: { content: "TailAdmin", level: 3 },
                        styles: { fontSize: "20px", fontWeight: "700", color: "#ffffff", fontFamily: "Inter" },
                        x: 0, y: 0, w: 150, h: 30,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                    {
                        id: "__t2_search__",
                        type: "input",
                        label: "Search Input",
                        props: { placeholder: "Type to search...", inputType: "text" },
                        styles: {
                            padding: "10px 16px",
                            border: "1px solid #334155",
                            borderRadius: "8px",
                            fontSize: "14px",
                            backgroundColor: "#1e293b",
                            color: "#ffffff",
                        },
                        x: 0, y: 0, w: 300, h: 40,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                ],
            },
        ],
    },
    // ─── Main Dashboard Body ───
    {
        type: "columns",
        label: "Dashboard Layout",
        props: { columnCount: 2 },
        styles: { display: "flex", gap: "0", padding: "0", minHeight: "700px" },
        x: 0, y: 64, w: 1280, h: 700,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [
            // Sidebar
            {
                id: "__t2_sidebar__",
                type: "container",
                label: "Sidebar",
                props: {},
                styles: {
                    padding: "24px 16px",
                    backgroundColor: "#1c2434",
                    minHeight: "700px",
                    border: "none",
                    borderRadius: "0",
                },
                x: 0, y: 0, w: 280, h: 700,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [
                    {
                        id: "__t2_menu_label__",
                        type: "text",
                        label: "Menu Label",
                        props: { content: "MENU" },
                        styles: { fontSize: "12px", fontWeight: "600", color: "#8a99af", letterSpacing: "0.05em", fontFamily: "Inter" },
                        x: 0, y: 0, w: 248, h: 20,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                    {
                        id: "__t2_sidebar_menu__",
                        type: "stack",
                        label: "Sidebar Menu",
                        props: { direction: "vertical" },
                        styles: { display: "flex", flexDirection: "column", gap: "4px", padding: "12px 0", minHeight: "40px" },
                        x: 0, y: 30, w: 248, h: 300,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [
                            {
                                id: "__t2_mi_dashboard__",
                                type: "button",
                                label: "Dashboard Link",
                                props: { label: "📊  Dashboard" },
                                styles: { backgroundColor: "rgba(59,130,246,0.1)", color: "#3b82f6", padding: "12px 16px", borderRadius: "8px", fontSize: "14px", fontWeight: "500", border: "none", textAlign: "left", display: "block" },
                                x: 0, y: 0, w: 248, h: 44,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                            {
                                id: "__t2_mi_profile__",
                                type: "button",
                                label: "Profile Link",
                                props: { label: "👤  Profile" },
                                styles: { backgroundColor: "transparent", color: "#8a99af", padding: "12px 16px", borderRadius: "8px", fontSize: "14px", fontWeight: "500", border: "none", textAlign: "left", display: "block" },
                                x: 0, y: 0, w: 248, h: 44,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                            {
                                id: "__t2_mi_forms__",
                                type: "button",
                                label: "Forms Link",
                                props: { label: "📝  Forms" },
                                styles: { backgroundColor: "transparent", color: "#8a99af", padding: "12px 16px", borderRadius: "8px", fontSize: "14px", fontWeight: "500", border: "none", textAlign: "left", display: "block" },
                                x: 0, y: 0, w: 248, h: 44,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                            {
                                id: "__t2_mi_tables__",
                                type: "button",
                                label: "Tables Link",
                                props: { label: "📋  Tables" },
                                styles: { backgroundColor: "transparent", color: "#8a99af", padding: "12px 16px", borderRadius: "8px", fontSize: "14px", fontWeight: "500", border: "none", textAlign: "left", display: "block" },
                                x: 0, y: 0, w: 248, h: 44,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                            {
                                id: "__t2_mi_settings__",
                                type: "button",
                                label: "Settings Link",
                                props: { label: "⚙️  Settings" },
                                styles: { backgroundColor: "transparent", color: "#8a99af", padding: "12px 16px", borderRadius: "8px", fontSize: "14px", fontWeight: "500", border: "none", textAlign: "left", display: "block" },
                                x: 0, y: 0, w: 248, h: 44,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                        ],
                    },
                ],
            },
            // Main Content
            {
                id: "__t2_main__",
                type: "container",
                label: "Main Content",
                props: {},
                styles: {
                    padding: "24px",
                    backgroundColor: "#f1f5f9",
                    border: "none",
                    borderRadius: "0",
                    flex: "1",
                },
                x: 280, y: 0, w: 1000, h: 700,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [
                    {
                        id: "__t2_page_title__",
                        type: "title",
                        label: "Page Title",
                        props: { content: "eCommerce Dashboard", level: 2 },
                        styles: { fontSize: "26px", fontWeight: "700", color: "#1c2434", fontFamily: "Inter" },
                        x: 0, y: 0, w: 952, h: 40,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                    {
                        id: "__t2_metrics_grid__",
                        type: "columns",
                        label: "Metrics Grid",
                        props: { columnCount: 4 },
                        styles: { display: "flex", gap: "16px", padding: "24px 0", minHeight: "120px" },
                        x: 0, y: 50, w: 952, h: 140,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [
                            {
                                id: "__t2_m1__",
                                type: "container",
                                label: "Total Views",
                                props: {},
                                styles: { padding: "20px", backgroundColor: "#ffffff", borderRadius: "12px", border: "1px solid #e2e8f0" },
                                x: 0, y: 0, w: 226, h: 120,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [
                                    { id: "__t2_m1_val__", type: "title", label: "Metric Value", props: { content: "$3,456K", level: 3 }, styles: { fontSize: "28px", fontWeight: "700", color: "#1c2434", fontFamily: "Inter" }, x: 0, y: 0, w: 186, h: 35, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                    { id: "__t2_m1_lbl__", type: "text", label: "Metric Label", props: { content: "Total Views" }, styles: { fontSize: "13px", color: "#64748b", fontFamily: "Inter" }, x: 0, y: 40, w: 186, h: 20, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                    { id: "__t2_m1_pct__", type: "text", label: "Change %", props: { content: "↑ 0.43%" }, styles: { fontSize: "13px", color: "#22c55e", fontWeight: "500", fontFamily: "Inter" }, x: 0, y: 65, w: 186, h: 20, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                ],
                            },
                            {
                                id: "__t2_m2__",
                                type: "container",
                                label: "Total Profit",
                                props: {},
                                styles: { padding: "20px", backgroundColor: "#ffffff", borderRadius: "12px", border: "1px solid #e2e8f0" },
                                x: 0, y: 0, w: 226, h: 120,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [
                                    { id: "__t2_m2_val__", type: "title", label: "Metric Value", props: { content: "$45,200", level: 3 }, styles: { fontSize: "28px", fontWeight: "700", color: "#1c2434", fontFamily: "Inter" }, x: 0, y: 0, w: 186, h: 35, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                    { id: "__t2_m2_lbl__", type: "text", label: "Metric Label", props: { content: "Total Profit" }, styles: { fontSize: "13px", color: "#64748b", fontFamily: "Inter" }, x: 0, y: 40, w: 186, h: 20, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                    { id: "__t2_m2_pct__", type: "text", label: "Change %", props: { content: "↑ 4.35%" }, styles: { fontSize: "13px", color: "#22c55e", fontWeight: "500", fontFamily: "Inter" }, x: 0, y: 65, w: 186, h: 20, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                ],
                            },
                            {
                                id: "__t2_m3__",
                                type: "container",
                                label: "Total Products",
                                props: {},
                                styles: { padding: "20px", backgroundColor: "#ffffff", borderRadius: "12px", border: "1px solid #e2e8f0" },
                                x: 0, y: 0, w: 226, h: 120,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [
                                    { id: "__t2_m3_val__", type: "title", label: "Metric Value", props: { content: "2,450", level: 3 }, styles: { fontSize: "28px", fontWeight: "700", color: "#1c2434", fontFamily: "Inter" }, x: 0, y: 0, w: 186, h: 35, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                    { id: "__t2_m3_lbl__", type: "text", label: "Metric Label", props: { content: "Total Products" }, styles: { fontSize: "13px", color: "#64748b", fontFamily: "Inter" }, x: 0, y: 40, w: 186, h: 20, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                    { id: "__t2_m3_pct__", type: "text", label: "Change %", props: { content: "↑ 2.59%" }, styles: { fontSize: "13px", color: "#22c55e", fontWeight: "500", fontFamily: "Inter" }, x: 0, y: 65, w: 186, h: 20, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                ],
                            },
                            {
                                id: "__t2_m4__",
                                type: "container",
                                label: "Total Users",
                                props: {},
                                styles: { padding: "20px", backgroundColor: "#ffffff", borderRadius: "12px", border: "1px solid #e2e8f0" },
                                x: 0, y: 0, w: 226, h: 120,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [
                                    { id: "__t2_m4_val__", type: "title", label: "Metric Value", props: { content: "3,456", level: 3 }, styles: { fontSize: "28px", fontWeight: "700", color: "#1c2434", fontFamily: "Inter" }, x: 0, y: 0, w: 186, h: 35, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                    { id: "__t2_m4_lbl__", type: "text", label: "Metric Label", props: { content: "Total Users" }, styles: { fontSize: "13px", color: "#64748b", fontFamily: "Inter" }, x: 0, y: 40, w: 186, h: 20, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                    { id: "__t2_m4_pct__", type: "text", label: "Change %", props: { content: "↓ 0.95%" }, styles: { fontSize: "13px", color: "#ef4444", fontWeight: "500", fontFamily: "Inter" }, x: 0, y: 65, w: 186, h: 20, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                ],
                            },
                        ],
                    },
                    // Chart placeholder
                    {
                        id: "__t2_chart__",
                        type: "container",
                        label: "Chart Area",
                        props: {},
                        styles: { padding: "24px", backgroundColor: "#ffffff", borderRadius: "12px", border: "1px solid #e2e8f0", minHeight: "300px" },
                        x: 0, y: 210, w: 952, h: 320,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [
                            { id: "__t2_chart_title__", type: "title", label: "Chart Title", props: { content: "Revenue Overview", level: 4 }, styles: { fontSize: "18px", fontWeight: "600", color: "#1c2434", fontFamily: "Inter" }, x: 0, y: 0, w: 904, h: 30, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                            { id: "__t2_chart_sub__", type: "text", label: "Chart Subtitle", props: { content: "Monthly revenue for the current year" }, styles: { fontSize: "13px", color: "#64748b", fontFamily: "Inter" }, x: 0, y: 35, w: 904, h: 20, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                            {
                                id: "__t2_chart_placeholder__",
                                type: "shape",
                                label: "Chart Placeholder",
                                props: { shapeType: "rectangle" },
                                styles: { backgroundColor: "#f8fafc", borderRadius: "8px" },
                                x: 0, y: 70, w: 904, h: 210,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                        ],
                    },
                ],
            },
        ],
    },
];

// ═══════════════════════════════════════════════════════════
// Template 3 — Eldora UI: Portfolio
// ═══════════════════════════════════════════════════════════
const template3Elements: any[] = [
    // ─── Hero / Intro Section ───
    {
        type: "section",
        label: "Portfolio Hero",
        props: {},
        styles: {
            padding: "0",
            minHeight: "100vh",
            background: "linear-gradient(180deg, #000000 0%, #0a0a0a 100%)",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
        },
        x: 0, y: 0, w: 1280, h: 700,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [
            {
                id: "__t3_nav__",
                type: "container",
                label: "Navigation",
                props: {},
                styles: {
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    padding: "20px 60px",
                    backgroundColor: "transparent",
                    border: "none",
                    position: "absolute",
                    top: "0",
                    width: "100%",
                },
                x: 0, y: 0, w: 1280, h: 60,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [
                    {
                        id: "__t3_name__",
                        type: "title",
                        label: "Name",
                        props: { content: "John Doe", level: 3 },
                        styles: { fontSize: "18px", fontWeight: "600", color: "#ffffff", fontFamily: "Inter" },
                        x: 0, y: 0, w: 150, h: 30,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                    {
                        id: "__t3_nav_links__",
                        type: "menu",
                        label: "Nav Links",
                        props: { items: "About,Work,Blog,Contact", menuStyle: "horizontal" },
                        styles: { display: "flex", gap: "32px", padding: "0" },
                        x: 0, y: 0, w: 350, h: 30,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                ],
            },
            {
                id: "__t3_hero_content__",
                type: "container",
                label: "Hero Content",
                props: {},
                styles: {
                    padding: "0 60px",
                    textAlign: "center",
                    maxWidth: "900px",
                    backgroundColor: "transparent",
                    border: "none",
                },
                x: 190, y: 180, w: 900, h: 350,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [
                    {
                        id: "__t3_greeting__",
                        type: "text",
                        label: "Greeting",
                        props: { content: "Hi, I'm" },
                        styles: { fontSize: "18px", color: "#a1a1aa", textAlign: "center", fontFamily: "Inter" },
                        x: 0, y: 0, w: 780, h: 25,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                    {
                        id: "__t3_big_name__",
                        type: "title",
                        label: "Big Name",
                        props: { content: "John Doe", level: 1 },
                        styles: {
                            fontSize: "72px",
                            fontWeight: "800",
                            color: "#ffffff",
                            textAlign: "center",
                            lineHeight: "1.1",
                            fontFamily: "Inter",
                            letterSpacing: "-0.03em",
                        },
                        x: 0, y: 35, w: 780, h: 90,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                    {
                        id: "__t3_role__",
                        type: "title",
                        label: "Role",
                        props: { content: "Full Stack Developer", level: 2 },
                        styles: {
                            fontSize: "36px",
                            fontWeight: "700",
                            background: "linear-gradient(90deg, #6366f1, #a855f7, #ec4899)",
                            WebkitBackgroundClip: "text",
                            color: "#a78bfa",
                            textAlign: "center",
                            fontFamily: "Inter",
                        },
                        x: 0, y: 135, w: 780, h: 50,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                    {
                        id: "__t3_bio__",
                        type: "paragraph",
                        label: "Bio",
                        props: { content: "I'm a passionate developer who loves creating beautiful, performant web applications. Specializing in React, Next.js, and modern web technologies." },
                        styles: {
                            fontSize: "16px",
                            color: "#a1a1aa",
                            textAlign: "center",
                            lineHeight: "1.7",
                            fontFamily: "Inter",
                        },
                        x: 0, y: 200, w: 780, h: 60,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                    {
                        id: "__t3_socials__",
                        type: "socialbar",
                        label: "Social Links",
                        props: { facebook: false, twitter: true, instagram: false, linkedin: true, youtube: false, iconSize: 24, iconStyle: "outline" },
                        styles: { display: "flex", gap: "16px", alignItems: "center", justifyContent: "center" },
                        x: 300, y: 280, w: 180, h: 48,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [],
                    },
                ],
            },
        ],
    },
    // ─── Projects Section ───
    {
        type: "section",
        label: "Projects Section",
        props: {},
        styles: {
            padding: "80px 60px",
            minHeight: "500px",
            backgroundColor: "#0a0a0a",
        },
        x: 0, y: 700, w: 1280, h: 600,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [
            {
                id: "__t3_proj_heading__",
                type: "title",
                label: "Projects Heading",
                props: { content: "Featured Projects", level: 2 },
                styles: { fontSize: "36px", fontWeight: "700", color: "#ffffff", textAlign: "center", fontFamily: "Inter" },
                x: 0, y: 0, w: 1160, h: 50,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
            {
                id: "__t3_proj_grid__",
                type: "columns",
                label: "Projects Grid",
                props: { columnCount: 2 },
                styles: { display: "flex", gap: "24px", padding: "40px 0", minHeight: "350px" },
                x: 0, y: 70, w: 1160, h: 450,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [
                    {
                        id: "__t3_p1__",
                        type: "container",
                        label: "Project 1",
                        props: {},
                        styles: { padding: "0", backgroundColor: "#18181b", borderRadius: "16px", border: "1px solid #27272a", overflow: "hidden" },
                        x: 0, y: 0, w: 560, h: 350,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [
                            {
                                id: "__t3_p1_img__",
                                type: "image",
                                label: "Project Image",
                                props: { src: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=300&fit=crop", alt: "Project 1", objectFit: "cover" },
                                styles: { maxWidth: "100%", borderRadius: "0", display: "block" },
                                x: 0, y: 0, w: 560, h: 200,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                            {
                                id: "__t3_p1_info__",
                                type: "container",
                                label: "Project Info",
                                props: {},
                                styles: { padding: "20px", backgroundColor: "transparent", border: "none" },
                                x: 0, y: 200, w: 560, h: 150,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [
                                    { id: "__t3_p1_title__", type: "title", label: "Project Title", props: { content: "E-Commerce Platform", level: 3 }, styles: { fontSize: "20px", fontWeight: "600", color: "#ffffff", fontFamily: "Inter" }, x: 0, y: 0, w: 520, h: 30, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                    { id: "__t3_p1_desc__", type: "text", label: "Project Desc", props: { content: "Full-stack e-commerce with React, Node.js, and Stripe" }, styles: { fontSize: "14px", color: "#a1a1aa", lineHeight: "1.5", fontFamily: "Inter" }, x: 0, y: 35, w: 520, h: 25, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                    { id: "__t3_p1_btn__", type: "button", label: "View Project", props: { label: "View Project →" }, styles: { backgroundColor: "transparent", color: "#a78bfa", padding: "8px 0", borderRadius: "0", fontSize: "14px", fontWeight: "500", border: "none", cursor: "pointer", textAlign: "left" }, x: 0, y: 70, w: 140, h: 36, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                ],
                            },
                        ],
                    },
                    {
                        id: "__t3_p2__",
                        type: "container",
                        label: "Project 2",
                        props: {},
                        styles: { padding: "0", backgroundColor: "#18181b", borderRadius: "16px", border: "1px solid #27272a", overflow: "hidden" },
                        x: 0, y: 0, w: 560, h: 350,
                        opacity: 1, rotation: 0, visible: true, locked: false,
                        children: [
                            {
                                id: "__t3_p2_img__",
                                type: "image",
                                label: "Project Image",
                                props: { src: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=600&h=300&fit=crop", alt: "Project 2", objectFit: "cover" },
                                styles: { maxWidth: "100%", borderRadius: "0", display: "block" },
                                x: 0, y: 0, w: 560, h: 200,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [],
                            },
                            {
                                id: "__t3_p2_info__",
                                type: "container",
                                label: "Project Info",
                                props: {},
                                styles: { padding: "20px", backgroundColor: "transparent", border: "none" },
                                x: 0, y: 200, w: 560, h: 150,
                                opacity: 1, rotation: 0, visible: true, locked: false,
                                children: [
                                    { id: "__t3_p2_title__", type: "title", label: "Project Title", props: { content: "AI Dashboard", level: 3 }, styles: { fontSize: "20px", fontWeight: "600", color: "#ffffff", fontFamily: "Inter" }, x: 0, y: 0, w: 520, h: 30, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                    { id: "__t3_p2_desc__", type: "text", label: "Project Desc", props: { content: "Machine learning analytics dashboard with real-time data" }, styles: { fontSize: "14px", color: "#a1a1aa", lineHeight: "1.5", fontFamily: "Inter" }, x: 0, y: 35, w: 520, h: 25, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                    { id: "__t3_p2_btn__", type: "button", label: "View Project", props: { label: "View Project →" }, styles: { backgroundColor: "transparent", color: "#a78bfa", padding: "8px 0", borderRadius: "0", fontSize: "14px", fontWeight: "500", border: "none", cursor: "pointer", textAlign: "left" }, x: 0, y: 70, w: 140, h: 36, opacity: 1, rotation: 0, visible: true, locked: false, children: [] },
                                ],
                            },
                        ],
                    },
                ],
            },
        ],
    },
    // ─── Contact Section ───
    {
        type: "section",
        label: "Contact Section",
        props: {},
        styles: {
            padding: "80px 60px",
            minHeight: "400px",
            backgroundColor: "#000000",
            textAlign: "center",
        },
        x: 0, y: 1300, w: 1280, h: 400,
        opacity: 1, rotation: 0, visible: true, locked: false,
        children: [
            {
                id: "__t3_contact_heading__",
                type: "title",
                label: "Contact Heading",
                props: { content: "Let's Work Together", level: 2 },
                styles: { fontSize: "40px", fontWeight: "700", color: "#ffffff", textAlign: "center", fontFamily: "Inter" },
                x: 0, y: 0, w: 1160, h: 50,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
            {
                id: "__t3_contact_text__",
                type: "paragraph",
                label: "Contact Text",
                props: { content: "Have a project in mind? Let's chat about how we can bring your ideas to life." },
                styles: { fontSize: "18px", color: "#a1a1aa", textAlign: "center", lineHeight: "1.7", fontFamily: "Inter" },
                x: 0, y: 60, w: 1160, h: 40,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
            {
                id: "__t3_contact_btn__",
                type: "button",
                label: "Contact Button",
                props: { label: "Get in Touch →" },
                styles: {
                    backgroundColor: "#a78bfa",
                    color: "#000000",
                    padding: "14px 36px",
                    borderRadius: "999px",
                    fontSize: "16px",
                    fontWeight: "600",
                    border: "none",
                    cursor: "pointer",
                    textAlign: "center",
                },
                x: 520, y: 140, w: 200, h: 50,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
            {
                id: "__t3_footer__",
                type: "text",
                label: "Footer",
                props: { content: "© 2026 John Doe. All rights reserved." },
                styles: { fontSize: "13px", color: "#52525b", textAlign: "center", fontFamily: "Inter" },
                x: 0, y: 220, w: 1160, h: 25,
                opacity: 1, rotation: 0, visible: true, locked: false,
                children: [],
            },
        ],
    },
];

// ═══════════════════════════════════════════════════════════
// Export all site templates
// ═══════════════════════════════════════════════════════════
export const siteTemplates: SiteTemplate[] = [
    {
        id: "open-landing",
        name: "Open — SaaS Landing",
        description: "Modern dark SaaS landing page with hero, features grid, and CTA sections. Perfect for startups and developer tools.",
        category: "Landing Page",
        thumbnail: "https://github.com/user-attachments/assets/522a5e46-2a0e-48ca-80eb-87c7fa58f3ea",
        previewUrl: "https://open.cruip.com/",
        elements: template1Elements,
    },
    {
        id: "tailadmin-dashboard",
        name: "TailAdmin — Dashboard",
        description: "Professional admin dashboard with sidebar navigation, metric cards, and chart placeholders. Ideal for data-rich backends.",
        category: "Dashboard",
        thumbnail: "https://github.com/user-attachments/assets/265fa13e-98ed-4c99-bd7f-ce7efe19627f",
        previewUrl: "https://free-demo.tailadmin.com/",
        elements: template2Elements,
    },
    {
        id: "eldora-portfolio",
        name: "Eldora — Portfolio",
        description: "Minimalist dark portfolio with animated hero, project showcase, and contact section. Built for developers and designers.",
        category: "Portfolio",
        thumbnail: "https://github.com/user-attachments/assets/265fa13e-98ed-4c99-bd7f-ce7efe19627f",
        previewUrl: "https://www.eldoraui.site/",
        elements: template3Elements,
    },
];
