// ═══════════════════════════════════════════════════
// Code Generation — Express.js Templates
// ═══════════════════════════════════════════════════

export const PACKAGE_JSON_TEMPLATE = (name: string, port: number) => `{
  "name": "${name.toLowerCase().replace(/\\s+/g, "-")}",
  "version": "1.0.0",
  "description": "Generated by RanDoseru Backend Builder",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "dev": "nodemon server.js"
  },
  "dependencies": {
    "express": "^4.18.2",
    "mongoose": "^7.6.0",
    "cors": "^2.8.5",
    "dotenv": "^16.3.1",
    "helmet": "^7.1.0",
    "morgan": "^1.10.0",
    "bcryptjs": "^2.4.3",
    "jsonwebtoken": "^9.0.2",
    "express-rate-limit": "^7.1.4",
    "express-validator": "^7.0.1"
  },
  "devDependencies": {
    "nodemon": "^3.0.2"
  }
}`;

export const SERVER_TEMPLATE = (port: number, imports: string, middlewareSetup: string, routeSetup: string) => `
const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || ${port};

// ─── Built-in Middleware ───
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());
app.use(helmet());
app.use(morgan('dev'));

${middlewareSetup}

${imports}

// ─── Routes ───
${routeSetup}

// ─── Health Check ───
app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// ─── Error Handler ───
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(err.status || 500).json({
    error: {
      message: err.message || 'Internal Server Error',
      ...(process.env.NODE_ENV === 'development' && { stack: err.stack }),
    },
  });
});

// ─── Database Connection & Start ───
const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/${port === 3001 ? 'auth_db' : 'app_db'}';

mongoose.connect(MONGO_URI)
  .then(() => {
    console.log('✅ Connected to MongoDB');
    app.listen(PORT, () => {
      console.log(\`🚀 Server running on port \${PORT}\`);
    });
  })
  .catch((err) => {
    console.error('❌ MongoDB connection error:', err);
    process.exit(1);
  });

module.exports = app;
`.trim();

export const MODEL_TEMPLATE = (modelName: string, fields: string) => `
const mongoose = require('mongoose');

const ${modelName}Schema = new mongoose.Schema({
${fields}
}, {
  timestamps: true,
});

module.exports = mongoose.model('${modelName}', ${modelName}Schema);
`.trim();

export const ROUTE_TEMPLATE = (routeName: string, endpoints: string) => `
const express = require('express');
const router = express.Router();

${endpoints}

module.exports = router;
`.trim();

export const AUTH_MIDDLEWARE_TEMPLATE = () => `
const jwt = require('jsonwebtoken');

const auth = (req, res, next) => {
  try {
    const token = req.header('Authorization')?.replace('Bearer ', '');
    if (!token) {
      return res.status(401).json({ error: 'Access denied. No token provided.' });
    }

    const decoded = jwt.verify(token, process.env.JWT_SECRET || 'your-secret-key');
    req.user = decoded;
    next();
  } catch (error) {
    res.status(401).json({ error: 'Invalid token.' });
  }
};

module.exports = auth;
`.trim();

export const CONTROLLER_TEMPLATE = (modelName: string, routes: string) => `
const ${modelName} = require('../models/${modelName}');

${routes}
`.trim();

export const ENV_TEMPLATE = (vars: Record<string, string>) => {
  return Object.entries(vars)
    .map(([key, value]) => `${key}=${value}`)
    .join('\n');
};

export const DOCKERFILE_TEMPLATE = (port: number) => `
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

EXPOSE ${port}

CMD ["node", "server.js"]
`.trim();

export const DOCKER_COMPOSE_TEMPLATE = (services: { name: string; port: number }[]) => `
version: '3.8'

services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: app_db

${services.map(s => `  ${s.name.toLowerCase().replace(/\\s+/g, '-')}:
    build: ./${s.name.toLowerCase().replace(/\\s+/g, '-')}
    ports:
      - "${s.port}:${s.port}"
    environment:
      - PORT=${s.port}
      - MONGO_URI=mongodb://mongodb:27017/${s.name.toLowerCase().replace(/\\s+/g, '_')}_db
    depends_on:
      - mongodb
    restart: unless-stopped`).join('\n\n')}

volumes:
  mongo-data:
`.trim();

export const README_TEMPLATE = (projectName: string, services: { name: string; port: number; description: string }[]) => `
# ${projectName}

> Generated by RanDoseru Backend Builder

## Services

${services.map(s => `### ${s.name}
- **Port**: ${s.port}
- **Description**: ${s.description || 'No description'}
`).join('\n')}

## Getting Started

### Prerequisites
- Node.js 18+
- MongoDB

### Installation

\`\`\`bash
npm install
\`\`\`

### Development

\`\`\`bash
npm run dev
\`\`\`

### Docker

\`\`\`bash
docker-compose up -d
\`\`\`

## API Documentation

Health check: \`GET /health\`
`.trim();
